### ISSUE TITLE
Table same name as the module. Global events crashed.

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia-modules/TheliaStudio#19]
Hello,

If a table in the same name as the module, the global file event crashed.

Exemple module : DateExclude
table : date_exclude

File event global DateExcludeEvents crashed by table events DateExcludeEvents

Cheers,

**Comment by lovenunu** [comment]
:+1: You know ... This bug will produce a BC break :D

**Comment by gillesbourgeat** [comment]
==> [] :)
