### ISSUE TITLE
timestampable behaviour error

### ISSUE THREAD

**Issue by CodeMiner84** [thelia-modules/TheliaStudio#4]
When I'a using timestampable behaviour in schema, Loop method parseResults doesn't pass created_at and updated_at date to view and causes error by that.

**Comment by lovenunu** [comment]
Ohhh, good catch !
Here: https://github.com/thelia-modules/TheliaStudio/blob/master/Resources/Loop/Base/__TABLE__.php#L23

We see that we check if I18n behavior is present, but it must check timestampable.

**Comment by lovenunu** [comment]
Thanks !
