### ISSUE TITLE
Specific generation

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia-modules/TheliaStudio#6]
Hello,

Add the ability to generate specific files.

Exemple  command : php Thelia module:generate:loop table_name
Exemple  command : php Thelia module:generate:form table_name
...

Cheers,

**Comment by lovenunu** [comment]
What about a resources directory filter ?
Something like:

```
$ php Thelia module:generate:all -d Loop -t table_name ModuleName
```

As the Resources directory can cointain anything, I think we can't just create such specific commands, but we can filter :)
